### ISSUE TITLE
Legacy Fabric support?

### ISSUE THREAD

**Issue by Kichura** [LeviDevs/LunarClientSpoofer#6]
Is it possible for this mod to become [fabric supported on 1.8.9](https://github.com/Legacy-Fabric/fabric)?, Likely this request might get rejected for forge but still could be helpful for fabric clients so that people don't constantly ask you to play on lunar clients instead of just fabric.

**Comment by leafypout** [comment]
Forge is enough of a headache to work with (also why there hasn't been any updates due to Forge breaking completely for 1.7.10 as of like a month ago), I don't even know what Fabric is but I've heard that it's some sort of modding API (do we really need more modding API's?), I don't really care about it and I don't see how it's any different or better than Forge. Maintaining two different versions for different clients would be a massive headache and I don't even think there's a decent amount of people in the 1.7 community that even know what Fabric is. Their whole setup for developers also seems extremely over-complicated from looking at their website.

This mod might get turned into an executable that just injects into MC since Forge is already enough of a hassle to work with, in which case it would work on any MC client. Otherwise I'm probably never going to consider looking into supporting Fabric.
